settings:
  flat_accel: KDTree
  flat_accel_settings:
    s_a_heuristic:
      traversal_cost: 1
      intersection_cost: 1
    use_s_a_heuritic: false
    num_objects_terminate: 2
  light_sampler: RandomTriangle
  light_sampler_settings:
    binary_search_threshold: 2147483648
  dir_sampler: BRDF
  dir_sampler_settings:
    {}
  term_prob: MultiplierFunc
  term_prob_settings:
    # iters: 4
    exp: 1
    min_prob: 0.1
  rng: Uniform
  rng_settings:
    {}
  general_settings:
    computation_settings:
      {}
    back_cull_emission: false
