#pragma once

#include <QMainWindow>
#include <memory>

class Canvas;

namespace Ui {
class MainWindow;
}

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
  Q_OBJECT
public:
  MainWindow(QWidget *parent = 0);
  ~MainWindow() override;

private:
  // Auto-generated by Qt. DO NOT RENAME!
  Ui::MainWindow *ui;
};
